movie_forum_andre_ver/config/routes.rb
Rails.application.routes.draw do

  devise_for :usuarios
  resources :filmes do
  resources :reviews, except: [:show, :index]
  end

  root 'filmes#index'

end

movie_forum_andre_ver/app/models/filme.rb
class Filme < ActiveRecord::Base
  belongs_to :usuario
  has_many :reviews, dependent: :destroy

  has_attached_file :image, styles: { medium: "400x600#"}, default_url: "/assets/images/20-most-hilarious-movie-poster-remakes-15.jpg"  # inserir url default_url
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

end

movie_forum_andre_ver/app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :usuario
  belongs_to :filme
end

movie_forum_andre_ver/app/models/usuario.rb
class Usuario < ActiveRecord::Base
  # Include default devise modules.
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :filmes
  has_many :reviews,  dependent: :destroy
end

movie_forum_andre_ver/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

movie_forum_andre_ver/app/controllers/filmes_controller.rb
class FilmesController < ApplicationController
  before_action :set_filme, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_usuario!, except: [:index, :show]  # manda logar caso tente adicionar filme sem estar logado


  def index
    @filmes = Filme.all
  end

  def show
    @reviews = Review.where(filme_id: @filme.id).order("created_at DESC")

    if @review.blank?
      @avg_review = 0
    else
      @avg_review = @reviews.average(:rating).round(2)
    end
  end

  def new
    @filme = current_usuario.filmes.build
  end

  def edit
  end

  def create
    @filme = current_usuario.filmes.build(filme_params)

    respond_to do |format|
      if current_usuario.try(:admin?)
        @filme.save
        format.html { redirect_to @filme, notice: 'Filme was successfully created.' }
        format.json { render :show, status: :created, location: @filme }
      else
        format.html { render :new }
        format.json { render json: @filme.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /filmes/1
  # PATCH/PUT /filmes/1.json
  def update
    respond_to do |format|
      if current_usuario.try(:admin?)
        @filme.update(filme_params)
        format.html { redirect_to @filme, notice: 'Filme was successfully updated.' }
        format.json { render :show, status: :ok, location: @filme }
      else
        format.html { render :edit }
        format.json { render json: @filme.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /filmes/1
  # DELETE /filmes/1.json
  def destroy
    respond_to do |format|
      if current_usuario.try(:admin?)
        @filme.destroy
          format.html { redirect_to filmes_url, notice: 'Filme foi excluido com sucesso.' }
          format.json { head :no_content }
      else
          format.html { redirect_to filmes_url, notice: 'Permissão Negada' }
          format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_filme
      @filme = Filme.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def filme_params
      params.require(:filme).permit(:titulo, :descricao, :duracao, :diretor, :classificacao, :usuario_id, :image)
    end
end

movie_forum_andre_ver/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :set_filme
  before_action :authenticate_usuario!


  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)
    @review.usuario_id = current_usuario.id
    @review.filme_id = @filme.id
    respond_to do |format|
      if @review.save
        format.html { redirect_to @filme, notice: 'Review criado com sucesso!' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review atualizado com sucesso!' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review excluido com sucesso!' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end
    def set_filme
      @filme = Filme.find(params[:filme_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:rating, :comment)
    end
end

movie_forum_andre_ver/app/helpers/application_helper.rb
module ApplicationHelper
end

movie_forum_andre_ver/app/helpers/filmes_helper.rb
module FilmesHelper
end

movie_forum_andre_ver/app/helpers/reviews_helper.rb
module ReviewsHelper
end

movie_forum_andre_ver/app/views/filmes/_form.html.erb
<%= form_for@filme, html: {multipart: true} do |f| %>
<% if @filme.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@filme.errors.count, "error") %> prohibited this filme from being saved:</h2>

    <ul>
    <% @filme.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%if current_usuario.try(:admin?)%>
  <div class="field">
    <%= f.label :titulo %><br>
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :descricao %><br>
    <%= f.text_field :descricao %>
  </div>
  <div class="field">
    <%= f.label :duracao %><br>
    <%= f.text_field :duracao %>
  </div>
  <div class="field">
    <%= f.label :diretor %><br>
    <%= f.text_field :diretor %>
  </div>
  <div class="field">
    <%= f.label :classificacao %><br>
    <%= f.text_field :classificacao %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  <%end%>
<% end %>

movie_forum_andre_ver/app/views/filmes/edit.html.erb
<div class="crud-login">
  <h1>Editar Filme</h1>

  <%= render 'form' %>

  <%= link_to 'Exibir', @filme %> |
  <%= link_to 'Voltar', filmes_path %>

</div>

movie_forum_andre_ver/app/views/filmes/index.html.erb
<% if !usuario_signed_in? %>
  <div class="jumbotron">
    <h1>Seus filmes favoritos revisados!</h1>
    <p> Procurando um filme para aquele encontro? Para assistir em família? Para trolar seu irmão? Para se divertir? </p>
    <p> Saiba a qualidade dos filmes pela melhor crítica: a comunidade! </p>
    <p> Entre na comunidade online dos maníacos por filmes e compartilhe suas revisões conosco! </p>
    <p><%= link_to "Quero participar!", new_usuario_registration_path, class: "btn btn-primary btn-lg" %></p>
  </div>
<% end %>

<div class="row">
  <% @filmes.each do |filme| %>
    <div class="col-sm-6 col-md-3">
      <div class="thumbnail">
        <%= link_to (image_tag filme.image.url(:medium), class: 'Image'), filme %>
      </div>
    </div>
  <% end %>
</div>

movie_forum_andre_ver/app/views/filmes/new.html.erb
<div class="crud-login">
  <h1>Novo Filme</h1>

  <%= render 'form' %>

  <%= link_to 'Voltar', filmes_path %>
</div>

movie_forum_andre_ver/app/views/filmes/show.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <div class="row">
      <div class="col-md-4">
        <%= image_tag@filme.image.url(:medium) %>
        <div class="star-rating" data-score= <%= @avg_review %> ></div>
                <em><%= "#{@reviews.length} reviews" %></em>
        <div class="table-responsive">
          <table class="table">
            <tr>
              <td class="titulos"><strong>Titulo:</strong></td>
              <td><%= @filme.titulo %></td>
            </tr>
            <tr>
              <td class="titulos"><strong>Duração:</strong></td>
              <td><%= @filme.duracao %></td>
            </tr>
            <tr>
              <td class="titulos"><strong>Diretor:</strong></td>
              <td><%= @filme.diretor %></td>
            </tr>
            <tr>
              <td class="titulos"><strong>Classificacao:</strong></td>
              <td><%= @filme.classificacao %></td>
            </tr>
          </table>
          <%= link_to "Escreva o que achou do filme", new_filme_review_path(@filme) %>
        </div>
      </div>
      <div class="col-md-7 col-md-offset-1">
        <h1 class="review_title" style="color: #0b3365"><%= @filme.titulo %></h1>
        <p style="color: gray"><%= @filme.descricao %></p>
        <% if @reviews.blank? %>
          <h3>Até agora sem nenhuma revisão. Gostaria de ser o primeiro?</h3>
          <%= link_to "Escrever Revisão", new_filme_review_path(@filme), class: "btn btn-danger" %>
        <% else %>
          <% @reviews.each do |review| %>
            <div class="review">
              <div class="star-rating" data-score= <%= review.rating %> ></div>
              <p><%= review.comment %></p>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<%= link_to 'Voltar', filmes_path %>
<%if current_usuario.try(:admin?)%>
  <%= link_to 'Editar', edit_filme_path(@filme) %>
  <%= link_to 'Deletar', @filme, method: :delete, data: { confirm: 'Tem certeza?' } %>
<%end%>

<script>
  $('.star-rating').raty({
    path: '/assets/',
    readOnly: true,
    score: function(){
      return $(this).attr('data-score');
    }
  });
</script>

movie_forum_andre_ver/app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Mudar navegação</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Movie Maniac", root_path, class: "navbar-brand" %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <%if current_usuario.try(:admin?) %>
        <li><%= link_to "Sair", destroy_usuario_session_path, method: "delete" %></li>
        <li><%= link_to "Novo Filme", new_filme_path, class: "active" %></li>
        <li><%= link_to "Conta", edit_usuario_registration_path %></li>
        <% elsif usuario_signed_in? %>
          <li><%= link_to "Sair", destroy_usuario_session_path, method: "delete" %></li>
          <li><%= link_to "Conta", edit_usuario_registration_path %></li>
        <% else %>
          <li><%= link_to "Cadastre-se", new_usuario_registration_path, class: "active" %></li>
          <li><%= link_to "Login", new_usuario_session_path, class: "active" %></li>
        <% end %>
      </ul>
      <form class="navbar-form navbar-right" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Digite aqui o que deseja achar">
        </div>
        <button type="submit" class="btn btn-default" id="ache">Procurar</button>
      </form>
    </div>
  </div>
</nav>

movie_forum_andre_ver/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Movie Maniac - o seu fórum sobre filmes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <%= if flash.each do |nome, msg| %>
      <%= content_tag(:div, msg, class: "alert alert-info") %>
      <% end %>
    <% end %>
  <%= yield %>
  </div>
</body>
</html>

movie_forum_andre_ver/app/views/reviews/_form.html.erb
<%= form_for([@filme, @review]) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <div id="star-rating"></div>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<script>
  $('#star-rating').raty({
    path: '/assets/',
    scoreName: 'review[rating]'
  });
</script>

movie_forum_andre_ver/app/views/reviews/edit.html.erb
<div class="crud-login">
  <h1>Editar Review</h1>
  <%= render 'form' %>
  <%= link_to 'Back', filme_path(@movie) %>
</div>

movie_forum_andre_ver/app/views/reviews/new.html.erb
<div class="crud-login">
  <h1>Novo Review</h1>

  <%= render 'form' %>

  <%= link_to 'Back', filme_path(@filme) %>
</div>